MSP-2 - Navbar
Tyriix/mumo-front pull request #18
Opened 2023-10-23 16:05 UTC by juleenek

2023-10-26 18:27 UTC, Tyriix requested changes
Całość bardzo ładnie napisana, nie ma się do czego przyczepić 💯. Oby tak dalej 🥳

2023-10-26 18:27 UTC, Tyriix commented on src/components/buttons/button-components.scss
Wszystko bardzo ładnie napisane, lecz myśle, że dobrym pomysłem byłoby ukrycie przycisku do przescrollowania do góry, kiedy użytkownik jest na samej górze strony. Pokazywałby się dopiero wtedy, kiedy już trochę przescrollujemy.

2023-10-26 18:27 UTC, Tyriix commented on src/layout/header/navbar/navbar-mobile/NavbarMobile.tsx
Super napisane 😄👍

2023-10-28 09:02 UTC, juleenek commented on src/components/buttons/button-components.scss
Dzięki za uwagę! Naprawione 🔨

2023-10-28 09:52 UTC, merged