MSP-17 - Register Panel
Tyriix/mumo-front pull request #20
Opened 2023-10-26 17:41 UTC by Tyriix

2023-10-26 18:32 UTC, juleenek requested changes
Wszystko super! 👍 👍 🥳  Pytania i sugestie podobne w sumie do zadania z loginem

2023-10-26 18:32 UTC, juleenek commented on src/layout/register/register-section.scss
> +    width: 72em;
Podobnie jak u login, czy jest możliwość aby stworzyć zmienną która by zawierała tą wartość która się powtarza `72em` jako `$circle-size` czy coś takiego?

2023-10-26 18:32 UTC, juleenek commented on src/pages/login/index.tsx
> +//   const refOffer = useRef<HTMLDivElement>(null)
Ten plik będzie potrzebny jak już wejdzie routing yes?

2023-10-26 18:32 UTC, juleenek commented on src/router.tsx
> -    path: NOT_FOUND_PATH,
Podobne pytanie jak w login, why usunięty `Error`? :c

2023-10-28 09:50 UTC, Tyriix commented on src/layout/register/register-section.scss
> +    width: 72em;
Już zmienione tak jak w login 👍

2023-10-28 09:50 UTC, Tyriix commented on src/router.tsx
> -    path: NOT_FOUND_PATH,
Usunięty przez przypadek 😢

2023-10-28 10:48 UTC, merged